export const GET_MARKERS_LOAD_START = 'GET_MARKERS_LOAD_START';
export const GET_MARKERS_LOAD_END = 'GET_MARKERS_LOAD_END';
export const GET_VRBO_MARKERS_LOAD_START = 'GET_VRBO_MARKERS_LOAD_START';
export const GET_VRBO_MARKERS_LOAD_END = 'GET_VRBO_MARKERS_LOAD_END';

export const GET_VISIBLE_LISTINGS_LOAD_START = 'GET_VISIBLE_LISTINGS_LOAD_START';
export const GET_VISIBLE_LISTINGS_LOAD_END = 'GET_VISIBLE_LISTINGS_LOAD_END';

export const GET_VISIBLE_VRBO_LISTINGS_LOAD_START = 'GET_VISIBLE_VRBO_LISTINGS_LOAD_START';
export const GET_VISIBLE_VRBO_LISTINGS_LOAD_END = 'GET_VISIBLE_VRBO_LISTINGS_LOAD_END';

export const GET_MULTIPLE_MARKERS_CALL_LOAD_START = 'GET_MULTIPLE_MARKERS_CALL_LOAD_START';
export const GET_MULTIPLE_MARKERS_CALL_LOAD_END = 'GET_MULTIPLE_MARKERS_CALL_LOAD_END';

export const GET_SEARCH_LOAD_START = 'GET_SEARCH_LOAD_START';
export const GET_SEARCH_LOAD_END = 'GET_SEARCH_LOAD_END';

export const SEARCH_CHANGE = 'SEARCH_CHANGE';

export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_IS_USER_ALLOWED = 'SET_IS_USER_ALLOWED';
